### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by Bratemoj** [grantwinney/hide-comments-in-chrome-sites#11]
Here's a new site I'd like you to consider blocking:

http://www.vijesti.me

(please include any other relevant details)

**Comment by grantwinney** [comment]
Alright, looks like they're hidden now.

@Bratemoj can you confirm for me?

**Comment by grantwinney** [comment]
Well, I think it's fixed.. let me know if it's not.
