### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by whoshazzz** [grantwinney/hide-comments-in-chrome-sites#16]
Here's a new site I'd like you to consider blocking:

https://www.instagram.com/

(please include any other relevant details)

**Comment by grantwinney** [comment]
The extension already does block some elements:

```
{
    "pattern": "^https?://(.*[.])?instagram[.]com",
    "immediate": ".coreSpriteComment, .LGYDV, .gElp9, .sH9wk",
    "delay": ".coreSpriteComment, .LGYDV, .gElp9, .sH9wk"
},
```

Can you tell if there are other elements to hide? As far as I can tell, it's hiding them in Chrome:

![capture](https://user-images.githubusercontent.com/1354059/52812711-20681400-3066-11e9-90b8-ad80b3282a9b.PNG)

**Comment by grantwinney** [comment]
Let me know if you have more details.
