### ISSUE TITLE
Not blocking any comments on reddit for me

### ISSUE THREAD

**Issue by Abhishek-dev2** [grantwinney/hide-comments-in-chrome-sites#22]
Here's a new site I'd like you to consider blocking:

https://www.reddit.com

It used to work just fine on Reddit, but now it does not work. I have checked the filter list, and there is no mention of Reddit.

(please include any other relevant details)

**Comment by grantwinney** [comment]
The class names I was using changed I guess. Should work now (update the definitions). Let me know how it goes.

**Comment by Abhishek-dev2** [comment]
Thank you for the quick update.
