### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by ferremayorsantodomingo** [grantwinney/hide-comments-in-chrome-sites#26]
Here's a new site I'd like you to consider blocking:

https://www.facebook.com/ferremayoronline/photos/a.2191298614437226/2363269700573449/?type=3&theater

(please include any other relevant details)

**Comment by grantwinney** [comment]
Closing as dupe of https://github.com/grantwinney/hide-comments-in-chrome-sites/issues/25
