### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by ismagelskis** [grantwinney/hide-comments-in-chrome-sites#29]
I'd like to hide comments on my Facebook profile.:
https://www.facebook.com/ismagelskis

How do I do that with the plugin?

**Comment by grantwinney** [comment]
I've gotten a number of requests to block Facebook but I can't figure out which part of it needs blocking... it should already be blocked. Where are you still seeing comments? Is it only certain sections? Or after you've scrolled down the page for awhile do they start appearing? Thanks.

**Comment by ismagelskis** [comment]
Actual it does block the comments on the news feed as you'll see here https://www.screencast.com/t/3hlKUkHqa. But when I go to my own profile and see my own post, there the comments still does appear. See https://www.screencast.com/t/8kpco0U8Qgb

**Comment by grantwinney** [comment]
Thanks for the update @ismagelskis. I'll check it out when I get a chance.

**Comment by grantwinney** [comment]
I never found a reason for this particular one, but I've made some updates for Facebook since then... wondering if you still see your own comments?

**Comment by grantwinney** [comment]
Let me know if you still have issues. I haven't gotten a request to block Facebook in awhile, so maybe I'll finally got it. Probably wishful thinking... 🤞
