### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by scolak** [grantwinney/hide-comments-in-chrome-sites#39]
Here's a new site I'd like you to consider blocking:

https://www.index.hr

(please include any other relevant details)

**Comment by grantwinney** [comment]
I picked a random story and the comments are hidden for me... they just use the Facebook comment system which I've already blocked. Is there a particular page, or part of a page, you're seeing comments on?

**Comment by scolak** [comment]
Sorry everything is working, I've sent this before checking.
Facebook comments are off.
Thanks for this man :)

Stjepan Čolak

Sysadmin/DevOps

**Comment by grantwinney** [comment]
No problem. Glad to hear it. :) Let me know if you find any other issues.
