### ISSUE TITLE
Not working properly on Facebook

### ISSUE THREAD

**Issue by vgalisson** [grantwinney/hide-comments-in-chrome-sites#40]
Hi, thanks for your awesome extension !

Unfortunately, it doesn't work properly on Facebook (tested on Chromium and Firefox, only Ubuntu though).

### Current state:

It does hide the numbers of comments (see that there is nothing in the red box below) but the comments are still there :

![hidecomments](https://user-images.githubusercontent.com/22483199/70309287-78e2ea80-180d-11ea-95bf-1bad6ff32976.png)

---
From you `sites.json` files, `commentable_item` should be blocked but it's not, as the screen capture below shows:

![hidecomments2](https://user-images.githubusercontent.com/22483199/70309799-95cbed80-180e-11ea-831d-909ee49af849.png)

---
### Possible solution:

Maybe it is possible to use the `data-testid` attribute (see bottom of below image) and a regex expression to find `CommentsList` in it as this is the comments section that we want to be hidding. 
If not, I don't how often (if ever) they change the div class name `_3w53` which correspond to comments section. (I'm able to hide all by doing `display: none` on this class name).

![hidecomments3](https://user-images.githubusercontent.com/22483199/70310508-1c34ff00-1810-11ea-87e4-00914837ffdc.png)

Thanks !

**Comment by grantwinney** [comment]
Thanks for leaving me some details to dig into! I've gotten a handful of issues saying Facebook wasn't working, but every time I asked for more details... 🦗🦗🦗

I had to be careful because I don't really want to hide the votes along with the comments, but I _think_ it should work better now. Try updating the definitions and let me know how it goes!

**Comment by vgalisson** [comment]
Nice, it works perfectly !

![image](https://user-images.githubusercontent.com/22483199/71158678-a59ef500-2244-11ea-9fbd-a67224d7fb34.png)

Thank you for your add-on that helps me to stop the urge to read all the opinions I don't care of people I don't even know !

**Comment by grantwinney** [comment]
Lol, you're welcome. I had the same issue.. that's why I wrote it! Let me know if you run into anything else.

**Comment by vgalisson** [comment]
Hi it's me again, facebook seems to have change something because it doesn't work anymore.
From what I see, `UFI2CommentList` is not there anymore.

The best solution seems to hide the class `_3w53` (it didn't change since last time from what I see in my previous screenshot so I assume it is safe to say it won't in the near future).

Otherwise, hide each individual comment having `aria-label="Comment"` but I don't know if it will take longer to hide each comment one by one.

Hope it helps !
