### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by robotheart** [grantwinney/hide-comments-in-chrome-sites#42]
Here's a new site I'd like you to consider blocking:

https://www.metacritic.com

(please include any other relevant details)

**Comment by robotheart** [comment]
The user comments are really horrible and ruin the experience of the site. Ideally, it would be great to have the ability to toggle on/off either user or critic comments. Much appreciation for this great work!

**Comment by grantwinney** [comment]
That would be breaking some really fundamental parts of the site. Most of the sites I block have their "main" purpose, and then the comments are just added fluff. On a site like metacritic though, isn't the whole point to be able to read other viewers' comments?

If you use the Stylus extension, you could setup a stylesheet to either block the `.critic_reviews_module` or `.user_reviews_module` elements (for critic comments and user comments, respectively).

```
.user_reviews_module {
    display: none !important;
}
```

Or block them both at once by using their shared parent element:
```
.critic_user_reviews {
    display: none !important;
}
```

**Comment by grantwinney** [comment]
Let me know if you want to do that and have a question about it.. I'll try to help. :)

**Comment by robotheart** [comment]
Hey thank you so much for replying and explaining the situation! Let me
review this and I’ll get back to you if I need further help. Really
appreciate you looking into this!

**Comment by grantwinney** [comment]
You may have already figured it out or found a better solution, but I was meaning to write a little intro to stylus, and had it partly done, so I finished it up... maybe it'll help. 🤷‍♂️

https://grantwinney.com/using-css-and-stylus-to-bend-the-web-to-your-will/

**Comment by robotheart** [comment]
Oh nice thank you for sharing this!
