### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by anabeshin** [grantwinney/hide-comments-in-chrome-sites#43]
Here's a new site I'd like you to consider blocking:

https://vk.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
Fixed way back when... forgot to close.

https://github.com/grantwinney/hide-comments-in-chrome-sites/commit/d53938b7bde97be7916f4788fb54b3861e5b5927
