### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by hobhobuk** [grantwinney/hide-comments-in-chrome-sites#44]
Here's a new site I'd like you to consider blocking:

https://uk.ign.com

Games are so of the most toxic people in the world.
Please allow it on a site like this, so I do not need my eyes to melt.
Thanks!

**Comment by grantwinney** [comment]
This should be working now, if you update the definitions. Let me know how it goes!

**Comment by hobhobuk** [comment]
Perfect, thanks for the speedy action :)
