### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by janiosarmento** [grantwinney/hide-comments-in-chrome-sites#45]
Here's a new site I'd like you to consider blocking:

https://www.uol.com.br

It's a very important news portal in Brazil, and blocking the comments in it would be great (my sanity says thank you).

**Comment by grantwinney** [comment]
Alright, if you update the definitions on the options page, they should be blocked. Let me know how it goes!

**Comment by janiosarmento** [comment]
Thank you very much!
