### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by 300tocharacter** [grantwinney/hide-comments-in-chrome-sites#5]
Here's a new site I'd like you to consider blocking:

https://www.instagram.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
Ugh, didn't see this because GitHub won't notify me of issues on my own repos unless I'm "watching" them, and I wasn't watching this one. Sorry for the late response @300tocharacter.

I'll check it out and see what I can do.

**Comment by grantwinney** [comment]
Alright I think I got it. Try updating the definitions and see if comments are blocked.
