### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by benbenben05** [grantwinney/hide-comments-in-chrome-sites#50]
Here's a new site I'd like you to consider blocking:

https://www.lefigaro.fr

(please include any other relevant details)

**Comment by grantwinney** [comment]
Should be good to go! Open the options page and update the definitions, and let me know how it goes.

**Comment by benbenben05** [comment]
Thank you so much it works ! Great job
————

Benjamin Vigliotta
+33 (0)6 47 28 30 28



Il giorno ven 17 apr 2020 alle ore 15:19 Grant <notifications@github.com>
ha scritto:
