### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by Tcherikover** [grantwinney/hide-comments-in-chrome-sites#51]
Here's a new site I'd like you to consider blocking:

https://www.haaretz.co.il

(please include any other relevant details)

**Comment by grantwinney** [comment]
If you click the "update definitions" in options and try again, they should be blocked. The drop-down to arrange comments doesn't have anything i can grab on to in order to hide it, but the comments themselves are hidden.

**Comment by Tcherikover** [comment]
Tested. Perfect. Thanks a lot.

 

Cheers,

 

Shaul
