### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by janiosarmento** [grantwinney/hide-comments-in-chrome-sites#52]
Here's a new site I'd like you to consider blocking:

https://renatoterra.blogfolha.uol.com.br

Actually, `(.*)\.blogfolha\.uol\.com\.br` would be a better match, since this is a large network of blogs.

**Comment by grantwinney** [comment]
I guess do the "update definitions" in the options page and then try it again. I tested it a few times, but before I could verify that I fixed it, the site locked me out behind a paywall.

**Comment by janiosarmento** [comment]
Perfect, thanks!

(I use burles.co to bypass paywalls.)

**Comment by grantwinney** [comment]
Awesome, glad to hear it. :) Thanks for giving me a head start with that regex too.
