### ISSUE TITLE
fab

### ISSUE THREAD

**Issue by vikassingh90** [grantwinney/hide-comments-in-chrome-sites#55]
Here's a new site I'd like you to consider blocking:

https://www.facebook.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
If you update the extension, I pushed a change to the store (v 1.4.0) that should fix blocking comments for Facebook. Let me know how it goes.

**Comment by grantwinney** [comment]
Actually, I'm closing this repo and merging it with a different one, that holds the source code for this extension. If you're still having issues with Facebook, [let me know there](https://github.com/grantwinney/hide-comments-everywhere/issues/new). Thanks!
