### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by 0549499788** [grantwinney/hide-comments-in-chrome-sites#9]
Here's a new site I'd like you to consider blocking:

https://web.facebook.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
Are there any components or areas in particular that need blocking? I don't use Facebook so I'm unable to test it out. I do try to block quite a bit on Facebook, but it's a little tough since they (seem to) randomly generate element ids.

**Comment by grantwinney** [comment]
If you're able to get back to me with more details, I can reopen this and take a look at it. Thanks.
